version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: bhanu1234
      MYSQL_DATABASE: emp_db
    ports:
      - "3306:3306"
    networks:
      - my-network-new
    volumes:
      - my-volumes:/var/lib/mysql
    restart: always
    container_name: mysql

  jenkins-app:
    image: jenkins-app:v1
    restart: always
    networks:
      - my-network-new
    depends_on:
      - mysql-db
    ports:
      - "8090:8090"
    container_name: jenkins-app


volumes:
  my-volumes:

networks:
  my-network-new: